### ISSUE TITLE
[NOT AN ISSUE] Thank you for sharing your API with us!

### ISSUE THREAD

**Issue by esteves67** [gusfahmi/Whatsapp-API#1]
Hello @gusfahmi 

I just would like to say **THANK YOU SO MUCH** for making an API and keeping the code simple and understandable so people like me that is starting in javascript can learn how express works along with whatsapp-web.js!

I've been searching for months an API that uses whatsapp-web.js, but like yours with just a few lines of codes and not one thousand of lines of code! Idk how you did an API with just like 170 lines of code that works that good!

Since this is the best API i found for my use-case because its really lightweight and not alot of code, it will be really useful in my project, can i use it in my project :heart: ? 

Thank you again! :smile: :fist_oncoming: :rocket: :+1: :100:

**Comment by gusfahmi** [comment]
Hello @esteves67 
You are free to use my API and i cant wait to see your project. 😀
